In [7]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# importing dataset
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

# taking care of missing data
# in this case the missing data is filled with the mean
#from sklearn.preprocessing import Imputer
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(X[:, 1:3])

In [8]:
print(x)

[['France' 0.0 0.0]
 ['Spain' 0.0 1.0]
 ['Germany' 1.0 0.0]
 ['Spain' 0.0 1.0]
 ['Germany' 1.0 0.0]
 ['France' 0.0 0.0]
 ['Spain' 0.0 1.0]
 ['France' 0.0 0.0]
 ['Germany' 1.0 0.0]
 ['France' 0.0 0.0]]


In [9]:
# Encoding categorical data
# in this case the coutnries (France, Spain, Germany) will be respectively (0, 2, 1)
# we encode the data since the models learn from numbers
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
print(x)

[[1.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 1.0 0.0 1.0]
 [0.0 1.0 0.0 1.0 0.0]
 [0.0 0.0 1.0 0.0 1.0]
 [0.0 1.0 0.0 1.0 0.0]
 [1.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 1.0 0.0 1.0]
 [1.0 0.0 0.0 0.0 0.0]
 [0.0 1.0 0.0 1.0 0.0]
 [1.0 0.0 0.0 0.0 0.0]]


In [12]:
#encoding dependent variable (yes/no)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [15]:
#splitting the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [17]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 0.0 1.0 -0.5773502691896258 1.2909944487358056]
 [0.0 1.0 0.0 1.7320508075688774 -0.7745966692414834]
 [1.0 0.0 0.0 -0.5773502691896258 -0.7745966692414834]
 [0.0 0.0 1.0 -0.5773502691896258 1.2909944487358056]
 [0.0 0.0 1.0 -0.5773502691896258 1.2909944487358056]
 [1.0 0.0 0.0 -0.5773502691896258 -0.7745966692414834]
 [0.0 1.0 0.0 1.7320508075688774 -0.7745966692414834]
 [1.0 0.0 0.0 -0.5773502691896258 -0.7745966692414834]]


In [19]:
print(x_test)

[[0.0 1.0 0.0 1.7320508075688774 -0.7745966692414834]
 [1.0 0.0 0.0 -0.5773502691896258 -0.7745966692414834]]
